### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shadowwalker** [shadowwalker/next-pwa#18]
- [x] example with `next-i18next`
- [x] enable on dev - prevent rebuild SW on hot reload
- [x] new option of glob pattern to include/exclude files in public folder - currently it pre-cache everything in `public/`
- [x] conventional `workers` folder to write custom service worker code with webpack bundling
